### ISSUE TITLE
Frontend issues after 1.15.0 update

### ISSUE THREAD

**Issue by tardis221** [AllediaWordPress/UpStream#359] opened 2018-02-15 18:57 UTC
After upgrading to 1.15.0, the frontend is missing all project data on the home page (right side).

![image](https://user-images.githubusercontent.com/7571875/36275042-b69e6876-1257-11e8-9cdf-79c51ced842b.png)

Also, if you choose a project from the left side, the edit functions are missing. Cannot edit Task, Milestone, etc.. 

Also, the "Add" Task, Bug, Milestone, etc.. button is no longer working.
![image](https://user-images.githubusercontent.com/7571875/36275149-0737a5c2-1258-11e8-85c0-5bd7ef709156.png)

Current versions:
UpStream 1.15.0
UpStream Frontend Edit 1.4.3

**Comment by deenison** [comment] 2018-02-15 19:10
Hey @tardis221, thanks. Could you update your Frontend Edit plugin and see if the issue persists?
All of UpStream plugins were updated as well.

**Comment by upstreamplugin** [comment] 2018-02-15 19:12
@deenison Sorry - no Frontend Edit update triggered today

**Comment by upstreamplugin** [comment] 2018-02-15 19:19
@deenison Do you mind checking again quickly? I know we had a Frontend Edit release planned, right?

**Comment by tardis221** [comment] 2018-02-15 19:48
After applying all extension updates manually, the edit option re-appears, however, the main page is still missing the project data. 

![image](https://user-images.githubusercontent.com/7571875/36277495-14a436a6-125f-11e8-9d65-beae93229cf2.png)

![image](https://user-images.githubusercontent.com/7571875/36277587-4a75ff6c-125f-11e8-8e26-3beb32d6429a.png)


When editing the task on the frontend, the Save button doesn't do anything. The window just remains open
.
![image](https://user-images.githubusercontent.com/7571875/36277520-236b66aa-125f-11e8-9352-0654da6a4ce2.png)

**Comment by upstreamplugin** [comment] 2018-02-15 20:09
Hi @tardis221. Thanks for the report. I'm not able to re-create that in testing here.

Could you check whether you're running Frontend Edit 1.5? Also try clearing the browser cache

**Comment by deenison** [comment] 2018-02-15 20:09
Although the extensions were updated, their process of looking for new versions work slightly different the way WP does for traditional/regular plugins. There might be some delay until people get notified.
~
@tardis221 Sorry for these inconveniences. This might be cache related? I wasn't able to reproduce those issues so far.

**Comment by tardis221** [comment] 2018-02-16 12:40
@deenison Yes, I am using all of the latest extensions including Frontend Edit 1.5.0. I have tried on three different browsers (after cleared cache) and two different computers. Still no project data on the Frontend. 
Everything was working fine until the upStream 1.15.0 update.

After clearing the cache, the save button now attempts to save, but in doing so redirects me back to the hostname instead of the projects page. 

Example:
Main site URL is "http://sitename.com/mis"
Project named "telecom" has frontend url of "http://sitename.com/mis/?project=telecom
When the Save button is pressed, I am returned to http://sitename.com/dashboard

**Comment by deenison** [comment] 2018-02-19 13:09
I see, thanks @tardis221.
Could you please try to set up a testable environment [here](https://upstreamplugin.com/create-demo) with similar WP/UpStream settings you're using so we can see a bit closer what might be going on?

**Comment by tardis221** [comment] 2018-02-19 13:14
@deenison As time permits, yes, I would be happy to do so. In the meantime, I have reverted my environment back to the previous version.

**Comment by tardis221** [comment] 2018-02-27 14:33
@deenison I have tested using your Demo site and well as a brand new build of WP on my server. The problem is definitely within my WP database. Would you be able to point me in the right direction as to which item in the database might be causing this? I'd like to try to salvage my site. I've already optimized and repaired my database but there is still something triggering this issue. Or, do you know of a plugin or method of exporting / importing my database information only (Posts, Projects, media files, etc) without the WP settings? Perhaps a granular approach to rebuilding the site? Any suggestions would be appreciated. 

Other than that, you can close this issue out since it is solely within my database. - Thank you.

**Comment by deenison** [comment] 2018-02-28 22:48
Oh, I see @tardis221. Glad you're able to narrow down the issue a bit. Thanks for putting effort into this.

About what exactly could be breaking the env, it's really hard to tell here from "outside", since I would be only shooting in the dark.
I'm not convinced yet some funny raw-content-data on your DB could really be the trouble maker on this, but the first thing that came to mind though was perhaps particular changes in v1.15.0 are conflicting with some other plugin(s) you might be using for some reason?

On the backup side, modular-export in WP can be a bit tricky because there are a lot of dependencies amongst the "modules", but there are also a lot of 3rd-party plugins you could give it a try: [UpdraftPlus](https://updraftplus.com), [BackWPup](https://wordpress.org/plugins/backwpup) seems very interesting 

Does the [v1.15.1](https://github.com/upstreamplugin/UpStream/releases/tag/v1.15.1) still breaks as the previous version?

**Comment by stevejburge** [comment] 2018-06-09 12:54
Closing this as out-dated

**Closed by stevejburge** 2018-06-09 12:54 UTC
Labels: pending:awaiting feedback
